### ISSUE TITLE
Docker image is broken?

### ISSUE THREAD

**Issue by opti-mix** [Tiramisu-Compiler/tiramisu#221]
I downloaded the docker image from http://groups.csail.mit.edu/commit/software/TiramisuVM.zip 
 to try it out and when I unzip it I get the following:

```
bash-3.2$ unzip TiramisuVM.zip
Archive:  TiramisuVM.zip
warning [TiramisuVM.zip]:  4294967296 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  4294967296
  (attempting to re-compensate)
   creating: TiramisuVM/
  inflating: TiramisuVM/.DS_Store
   creating: __MACOSX/
   creating: __MACOSX/TiramisuVM/
  inflating: __MACOSX/TiramisuVM/._.DS_Store
   creating: TiramisuVM/Logs/
  inflating: TiramisuVM/Logs/VBox.log
  inflating: TiramisuVM/TiramisuVM.vbox
  inflating: TiramisuVM/TiramisuVM.vbox-prev
  inflating: TiramisuVM/TiramisuVM.vdi
  error:  invalid compressed data to inflate
```

Could you please provide a working docker image?

**Comment by rbaghdadi** [comment]
Hi,

This is strange. I'm able to unzip the file on my mac. It is probably some incompatibility in the zip utilities we are using. If you access to a mac maybe you can to unzip it there. I'm creating a new compressed file using tar. I should be able to upload it later tonight or early tomorrow.

**Comment by opti-mix** [comment]
I tested a bit more. If you use unzip provided by "brew" on Macs, you get the error I described above. But if you just use Finder and tell to unzip the folder then it works. Weird.

**Comment by rbaghdadi** [comment]
Thanks. I will upload a 2nd tar version anyway.
