### ISSUE TITLE
Julia interface?

### ISSUE THREAD

**Issue by montyvesselinov** [Tiramisu-Compiler/tiramisu#223]
Your paper mentions Julia interface. Is it going to be released?

**Comment by rbaghdadi** [comment]
Hi @montyvesselinov , yes indeed we have a prototype that generates Julia from Tiramisu but it is not publicly available as it is still in early-stage development. We are interested in having a robust integration of Tiramisu within Julia so if you are interested in this and you have resources to spend on this please let us know. We can share with you our prototype that you can start from.
