### ISSUE TITLE
Can Multi Convs or MatMuls be fused?

### ISSUE THREAD

**Issue by SingularMaster** [Tiramisu-Compiler/tiramisu#270]
Conv or Matmul can be fused with eltwise operations easily. I want to know if two Convs or Conv and Matmul can be fused? Because fusion can reduce memory footprint，so it benefits a lot to some Tensor Accelerators (e.g. TVA) if cascaded Convs can be fused. If this kind of fusion is available, can anyone provide an example?

**Comment by rbaghdadi** [comment]
Yes conv and conv van be fused. Look at the VGG example: https://github.com/Tiramisu-Compiler/tiramisu/tree/master/benchmarks/DNN/blocks/vggBlock

The code is in https://github.com/Tiramisu-Compiler/tiramisu/blob/master/benchmarks/DNN/blocks/vggBlock/vgg_block_generator_tiramisu.cpp

or look at conv https://github.com/Tiramisu-Compiler/tiramisu/tree/master/benchmarks/DNN/blocks/conv2

The code is in https://github.com/Tiramisu-Compiler/tiramisu/blob/master/benchmarks/DNN/blocks/conv2/conv_layer_generator_2_tiramisu.cpp
