### ISSUE TITLE
Does tiramisu support FPGA as backend hardware now?

### ISSUE THREAD

**Issue by sunxl1988** [Tiramisu-Compiler/tiramisu#321]
As your paper said, it has supported fpga until now, right?

**Comment by rbaghdadi** [comment]
Hi,

Yes Tiramisu has an FPGA backend. It is called FROST. FROST is not publicly available though. Currently, there are no plans for making it public in the near future.

**Comment by bjourne** [comment]
> Currently it targets (1) multicore X86 CPUs, (2) Nvidia GPUs, (3) Xilinx FPGAs (Vivado HLS) and (4) distributed machines (using MPI).

Isn't this incorrect then?

**Comment by rbaghdadi** [comment]
There is a backend and two papers that talk about the FPGA backend. It is not publicly available on github though since we can’t provide support for potential users.
________________________________
