### ISSUE TITLE
unstructured weight sparsity mentioned by the paper

### ISSUE THREAD

**Issue by ZuoMeng96** [Tiramisu-Compiler/tiramisu#333]
HI! I read the paper _TIRAMISU: A Polyhedral Compiler for Dense and Sparse Deep Learning_, which is submitted on 7 May 2020. The paper mentioned that TIRAMISU support unstructured weight sparsity, and is there any tutorial to show us how to make it.

**Comment by rbaghdadi** [comment]
Hi,
We don't have tutorials on how to use it, but the code is public. You an find it on 

https://github.com/Tiramisu-Compiler/tiramisu/tree/master/benchmarks/DNN/layers/convolution/direct/sparse

for convolution for example. You can find the VGG sparse implementaiton on 

https://github.com/Tiramisu-Compiler/tiramisu/tree/master/benchmarks/DNN/blocks/vggBlock/cpu

for example.

**Comment by ZuoMeng96** [comment]
> Hi,
> We don't have tutorials on how to use it, but the code is public. You an find it on
> 
> https://github.com/Tiramisu-Compiler/tiramisu/tree/master/benchmarks/DNN/layers/convolution/direct/sparse
> 
> for convolution for example. You can find the VGG sparse implementaiton on
> 
> https://github.com/Tiramisu-Compiler/tiramisu/tree/master/benchmarks/DNN/blocks/vggBlock/cpu
> 
> for example.

OK. Thanks!
