### ISSUE TITLE
Is there a possible way to limit the core number used of a generated tiramisu CPU kernel?

### ISSUE THREAD

**Issue by SubjectNoi** [Tiramisu-Compiler/tiramisu#343]
As the title, now I want to limit the core number used by a generated tiramisu kernel, as following:
```
        halide_set_num_threads(4);
        tiramisu::init("matmul");
	constant _m("M", expr((int32_t) M));
	constant _n("N", expr((int32_t) N));
	constant _k("K", expr((int32_t) K));
	var i("i", 0, _m), j("j", 0, _n), k("k", 0, _k);
	input A("A", {"i", "j"}, {M, K}, p_uint8);
	input B("B", {"i", "j"}, {K, N}, p_uint8);
	computation C_init("C_init", {i, j}, expr((uint8_t) 0));
	computation C("C", {i, j, k}, p_uint8);
	C.set_expression(C(i, j, k - 1) + A(i, k) * B(k, j));

	C.parallelize(i);
	
	C.vectorize(j, 32);

	C.after(C_init, j);

	buffer b_A("b_A", {expr(M), expr(K)}, p_uint8, a_input);
	buffer b_B("b_B", {expr(K), expr(N)}, p_uint8, a_input);
	buffer b_C("b_C", {expr(M), expr(N)}, p_uint8, a_output);
	
	A.store_in(&b_A);
	B.store_in(&b_B);
	C_init.store_in(&b_C, {i, j});
	C.store_in(&b_C, {i, j});

	tiramisu::codegen({&b_A, &b_B, &b_C}, "matmul.o");
```
I tried to invoke `halide_set_num_threads` at the beginning of the program, but it trigger a undefined reference, I wonder is there a way to set the maximum cpu core used for that `matmul` kernel?

I have several assumption that I want to try:
1. std::thread and set_affinity to the kernel
2. omp_set_num_threads (This is useless)

**Comment by SubjectNoi** [comment]
export HL_NUM_THREADS=x may not satisfy my requirement since I want to execute my kernel in a parallel way (Thus a global env may not enough to control the core affinity of the kernel, as I understand).

**Comment by rbaghdadi** [comment]
Hi,

Tiramisu uses Halide as a backend so any method that Halide uses to solve this problem should also apply to Tiramisu (given that parallelization is handled by the Halide runtime).

When you used halide_set_num_threads(4) you are using it in the code generator. You actually should use it in the wrapper code that calls the tiramisu generated code, because this call affects the Halide runtime. I have never used it so not sure if it will work or not.

The other method is to apply a loop split on the loop that you want to parallelize. Let's say you want to parallelize on X codes, then you can the outermost loop with a factor of N/X assuming N is the size of the outermost loop. If you do this, the new outermost loop will have X iterations and so if you parallelize it and if you have X cores then each thread will take one iteration.

**Comment by SubjectNoi** [comment]
I've tried halide_set_num_threads(4) in wrapper code under single thread scenerio, and it worked, thanks. And is it possible to set core number by this API in OpenMP parallel sections? or in multiple std::thread?

**Comment by rbaghdadi** [comment]
This call controls the Halide runtime which plays the same role as OpenMP.

Basically the Halide runtime is responsible for parallelizing the loops and this call will control how it is doing that.

I don't know how it will interact with OpenMP or the native thread library used in C++.

If this is important to you, the best thing would be to look at the Halide runtime code and see what does it do exactly, or maybe ask this question to the Halide community. They might be able to better help on this.

**Comment by SubjectNoi** [comment]
OK, thanks a lot.

**Comment by SubjectNoi** [comment]
Sorry for reopen this issue, I wonder is there an API to dump the origin C code of generated object file?

**Comment by rbaghdadi** [comment]
Yes, we generate Halide IR and use Halide to lower this IR. Halide has a C code generator. You need to look at the function tiramisu::codegen() and try to find the call to Halide to ask Halide to generate an object file. You need to slightly modify the options of that function to make it generate C (this is an option to the Halide code generation function). To figure out how to generate C in Halide, you need to look at the Halide documentation.

**Comment by SubjectNoi** [comment]
It's very appreciated for your rapid reply. Finally, I manage to use MPI to launch multiple tiramisu kernels with my expected CPU core to use. It's my assumption that multiple threads (OMP, std::thread) will share one JIT execution engine so the two kernels will still act in a serialized manner (despite I launch them simultaneously by parallel sections), however, for multiple processes (MPI), they will invoke independent execution engines thus I can actually launch and execute them simultaneously.
