### ISSUE TITLE
Specifying non perfect loop nests with Tiramisu

### ISSUE THREAD

**Issue by hw-yuexy** [Tiramisu-Compiler/tiramisu#421]
Hi,

I am trying to implement Jacobi-1D from Polybench using Tiramisu, and I had some trouble. Here is the original loop structure of the benchmark with statements being simplified:
```
for t = 0 to T
  for i1 = 1 to N - 1
    B[i1] = A[i1 - 1] + A[i1] + A[i1 + 1]
  for i2 = 1 to N - 1
    A[i2] = B[i2 - 1] + B[i2] + B[i2 + 1]
```

This is what I tried, T and N are macros representing the loop bounds:

```
var i1("i1", 1, N - 1), 
      i2("i2", 1, N - 1), 
      t("t", 0, T);

input A("A", {"i1"}, {N}, p_float32);
input B("B", {"i2"}, {N}, p_float32);

computation S1("S1", {t, i1}, A(i1 + 1) + A(i1) + A(i1 - 1));
computation S2("S2", {t, i2}, B(i2 + 1) + B(i2) + B(i2 - 1));

// ... buffer definition & call codegen function
```

When I compile and run this, the generated Halide representation from debug mode looks like:
```
...
 for (c1, 0, 100 - 0) {
  for (c3, 1, 99 - 1) {
   b_B[0 + (c3*1)] = ((float32)b_A[0 + ((c3 + 1)*1)] + (float32)b_A[0 + (c3*1)]) + (float32)b_A[0 + ((c3 - 1)*1)]
   b_A[0 + (c3*1)] =((float32)b_B[0 + ((c3 + 1)*1)] + (float32)b_B[0 + (c3*1)]) + (float32)b_B[0 + ((c3 - 1)*1)]
  }
 }
...
```

The i1 and i2 loops are automatically fused, even if their iterators are different variables. To make the loop nests structured in the intended way, I have to use the primitive `S2.after(S1, t);`.

I am wondering if this is the intended behavior, and if there are better ways to achieve this? My current implementation looks weird to myself because I am using a primitive to specify the "original computation", while primitives are usually used to transform the original computations. 

Any help on this is appreciated!

**Comment by rbaghdadi** [comment]
Hi,

Yes it is the intended beahviour! You have to specify the order of
computations by adding .after otherwise the order will be undefined.
