### ISSUE TITLE
Debug Macro

### ISSUE THREAD

**Issue by abeakkas** [Tiramisu-Compiler/tiramisu#51]
\_\_FILE\_\_ and \_\_LINE\_\_ macros point to this file (tiramisu_debug.cpp:41) instead of where function is called. We should implement it as a macro instead of a function.

https://github.com/Tiramisu-Compiler/tiramisu/blob/fed7a552f6f3f7b9da8597813691d3e336444bbf/src/tiramisu_debug.cpp#L38-L47

**Comment by rbaghdadi** [comment]
Yes I agree.

**Comment by abeakkas** [comment]
Fixed with https://github.com/Tiramisu-Compiler/tiramisu/pull/68
