### ISSUE TITLE
Possible error in squential_mm

### ISSUE THREAD

**Issue by rbaghdadi** [Tiramisu-Compiler/tiramisu#81]
In https://github.com/Tiramisu-Compiler/tiramisu/blob/ba82202acbbdbc2db61d5598599319e72bb53dc5/benchmarks/linear_algebra/sequential_mm/generator.cpp#L44 

Shouldn't A(i,j) be A(i,k) instead ?

**Comment by abeakkas** [comment]
The iteration spaces of this example is different than the gemm example. It's A[i, j], B[j, k], and C[k, l]. Thus when multiplying A and B reduction is over j dimension.
