### ISSUE TITLE
Some Travis Tests Fail

### ISSUE THREAD

**Issue by abeakkas** [Tiramisu-Compiler/tiramisu#82]
When travis tests are enabled in:
https://github.com/Tiramisu-Compiler/tiramisu/blob/22c6c094af8dafe4b1e880279b9ad234a702e51a/.travis.yml#L22
some tests fail every now and then (e.g test_10). The issue is probably about avx2 support on Travis machines, so we night need to specify the architecture in .travis.yml file.

**Comment by rbaghdadi** [comment]
This is solved now.
